package com.example.dermabsa.model

enum class BodyRegion {
    HEAD_FRONT, HEAD_BACK,
    NECK_FRONT, NECK_BACK,

    CHEST, ABDOMEN,          // Tronco Anteriore diviso
    UPPER_BACK, LOWER_BACK, // Torace/Addome e Schiena
    UPPER_ARM_LEFT_FRONT, UPPER_ARM_RIGHT_FRONT, UPPER_ARM_LEFT_BACK, UPPER_ARM_RIGHT_BACK,
    FOREARM_LEFT_FRONT, FOREARM_RIGHT_FRONT, FOREARM_LEFT_BACK, FOREARM_RIGHT_BACK,
    HAND_LEFT_FRONT, HAND_RIGHT_FRONT, HAND_LEFT_BACK, HAND_RIGHT_BACK,
    GENITALS,
    BUTTOCK_LEFT, BUTTOCK_RIGHT, // Glutei
    THIGH_LEFT_FRONT, THIGH_RIGHT_FRONT, THIGH_LEFT_BACK, THIGH_RIGHT_BACK, // Cosce
    LOWER_LEG_LEFT_FRONT, LOWER_LEG_RIGHT_FRONT, LOWER_LEG_LEFT_BACK, LOWER_LEG_RIGHT_BACK, // Gambe/Stinchi
    FOOT_LEFT_FRONT, FOOT_RIGHT_FRONT, FOOT_LEFT_BACK, FOOT_RIGHT_BACK
}